version: "3"
services:
    zentao-web:
        image: easysoft/zentao:${ZT_TAG}
        container_name: zentao-web
        env_file:
            - ./zentao.env
        ports:
            - "${ZT_WEB_PORT}:80"
        volumes:
            - ./data/zentao:/data
    # Debug Database
    zentao-mysql:
        image: mysql
        container_name: zentao-mysql
        ports:
            - "3306:3306"
        restart: always
        env_file:
            - ./mysql.env
        volumes:
          - ./config/sql:/docker-entrypoint-initdb.d/
          - ./data/mysql:/var/lib/mysql
